### ISSUE TITLE
pex install specific version

### ISSUE THREAD

**Issue by jmagnusson** [petere/pex#6]
It would be nice to be able to install specific versions of the extensions.

For example with the following syntax for the `.yml` package description:

```yaml
homepage: http://postgis.net/
latest_version: 2.2.2
versions:
  - 2.2.2:
    url: http://download.osgeo.org/postgis/source/postgis-2.2.2.tar.gz
    sha1: f82fa96c4c73e8a94091b51f2e528a8146b03597
  - 2.2.1:
    url: http://download.osgeo.org/postgis/source/postgis-2.2.1.tar.gz
    sha1: 615f86c34ed4431383432d34f4b6d558c71fb94f
```

The default would be to use the latest available version when installing. To override you would do:

```sh
pex install postgis@2.2.1
```

With above syntax it would be easy to install multiple packages at different versions:

```sh
pex install postgis@2.2.1 pg_jobmon pg_partman@2.3.0
```
